### PR TITLE
widen small integer eltype to avoid InexactError (fixes #15)

### LINKED ISSUE #15: Better type handling?
If you have an array of Int8, it is somewhat likely that the bottom right corner of the array will not fit into 8 bits.  Should we handle addition overflow better?
```julia
julia> iX = IntegralArray(rand(Int8, 10, 10))
ERROR: InexactError: trunc(Int8, 145)
```

### PR DESCRIPTION
**Pull request by jakewilliami**
Give `IntegralArray` a parametric constructor, and better handling of types which might potentially overflow.

P.S., I mention the wrong issue in a couple of my commits—I meant to mention issue #15; my apologies.

fixes #15

### CODE REVIEW

File: src/IntegralArrays.jl [hunk 1]
```diff
@@ -94,14 +93,28 @@ struct IntegralArray{T, N, A} <: AbstractArray{T, N}
...
+
+let smallints = (Int === Int64 ?
+                Union{Int8, UInt8, Int16, UInt16, Int32, UInt32} :
+                Union{Int8, UInt8, Int16, UInt16})
+    global IntegralArray
+    notsmallint(T::Type{<:Integer}) = T <: Signed ? Int : UInt
+    IntegralArray(A::AbstractArray{T}) where {T <: smallints} =
+        IntegralArray{_maybe_floattype(notsmallint(T))}(A)
+    IntegralArray(data::AbstractArray{T}, A::AbstractArray) where {T <: smallints} =
+        (U = _maybe_floattype(notsmallint(T)); IntegralArray{U}(U.(data), A))
```
Comment (johnnychen94) [inline src/IntegralArrays.jl:117]: The `IntegralArray(data, A)` version should be non-allocating, and `U.(data)` breaks this promise. We can directly throw an error when `T <: smallints` here.

File: test/runtests.jl [hunk 2]
```diff
@@ -78,6 +78,15 @@ end
         IntegralArray(X, X)
         @test iX == X == IntegralArray(reshape(1:25, 5, 5))
     end
+    
+    @testset "small types" begin
+        X = Int8.(collect(reshape(1:25, 5, 5)))
+        iX = similar(X)
+        iAa = IntegralArray(X)
+        iAb = IntegralArray(iX, X)
```
Comment (johnnychen94) [inline test/runtests.jl:86]: and thus this should still error

```suggestion
        @test_throws InexactError IntegralArray(iX, X)
```

**Review by johnnychen94 — COMMENTED** [review]
How about abusing the term `_maybe_floattype` a bit, and using `widen` here since it errors only during accumulation?

```julia
# small integer eltypes almost certainly hit overflow issues (#15)
const SmallInt = @static if Int === Int64
    Union{Int8, UInt8, Int16, UInt16, Int32, UInt32}
else
    Union{Int8, UInt8, Int16, UInt16}
end
_maybe_floattype(::Type{T}) where T<:SmallInt = widen(T)
```

File: src/IntegralArrays.jl (hunk 1 above)
Comment (johnnychen94) [inline src/IntegralArrays.jl:117]: Style suggestion:

```julia
# small integer eltypes almost certainly hit overflow issues (#15)
const SmallInt = @static if Int === Int64
    Union{Int8, UInt8, Int16, UInt16, Int32, UInt32}
else
    Union{Int8, UInt8, Int16, UInt16}
end
_widen(::Type{T}) where T<:SmallInt = T <: Signed ? Int : UInt
IntegralArray(A::AbstractArray{T}) where T<:SmallInt =
    IntegralArray{_maybe_floattype(_widen(T))}(A)
IntegralArray(data::AbstractArray{T}, A::AbstractArray) where T<:SmallInt =
    throw(ArgumentError("Small integer eltype $(T) would cause potential overflow issue, please use more bits for buffer array."))
```

**Review by johnnychen94 — APPROVED** [review]

**Comment by johnnychen94** [comment]
@jakewilliami nice work! It's so pleasant to review the changes.
